"""Helpers for stripping Claude Code command-wrapper noise from prompts."""

from __future__ import annotations

import re

_XML_TAG_RE = re.compile(r"<[^>]+>")
_ANSI_RE = re.compile(r"\x1b\[[0-9;]*m")
_NOISE_PATTERNS = [
    re.compile(r"Caveat:.*?unless the user explicitly asks you to\.?\s*", re.S),
    re.compile(r"DO NOT respond to these messages.*?$", re.M),
    re.compile(r"The messages below were generated by the user.*?\.\s*"),
    re.compile(r"explicitly asks you to\.?\s*"),
    re.compile(r"^\s*/\w[\w:-]*\s*$", re.M),
    re.compile(r"^\s*model\s*$", re.M),
    re.compile(r"Set model to.*?effort\s*"),
]


def clean_prompt_text(text: str) -> str:
    """Remove command-wrapper noise and normalize whitespace."""
    if not text:
        return ""
    cleaned = _XML_TAG_RE.sub("", text)
    cleaned = _ANSI_RE.sub("", cleaned)
    for pattern in _NOISE_PATTERNS:
        cleaned = pattern.sub("", cleaned)
    return re.sub(r"\s{2,}", " ", cleaned).strip()


def first_meaningful_prompt(*candidates: str) -> str:
    """Return the first candidate that still has user intent after cleaning."""
    for candidate in candidates:
        cleaned = clean_prompt_text(candidate)
        if cleaned:
            return cleaned
    return ""
